### ISSUE TITLE
ContextProvider is missing in DeckProps

### ISSUE THREAD

**Issue by rgazelot** [danmarshall/deckgl-typings#121]
According to the 7.1 release, a ContextProvider can be set on the Deck component.
https://github.com/visgl/deck.gl/blob/b0001340e53bcb77fbc5f08a94c13e08f4490e7a/docs/whats-new.md#use-react-map-gl-components-with-deckgl

I didn't find it in the types
https://github.com/danmarshall/deckgl-typings/blob/master/deck.gl__core/index.d.ts#L2265

Error: 
```
Type '{ children: Element[]; initialViewState: { longitude: number; latitude: number; zoom: number; maxZoom: number; minZoom: number; pitch: number; bearing: number; }; controller: true; style: { ...; }; ContextProvider: Provider<...>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DeckGL> & Readonly<DeckGLProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'ContextProvider' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DeckGL> & Readonly<DeckGLProps> & Readonly<{ children?: ReactNode; }>'.
```

Did I missed something?

**Comment by danmarshall** [comment]
Hello, it's probably not you, since these typings may be incomplete. Can you send a PR?

**Comment by rgazelot** [comment]
@danmarshall Thanks for the feedback, I'll setup a PR for that 👍
