### ISSUE TITLE
CompositeLayer.getSublayerProps return type should allow arbitrary props

### ISSUE THREAD

**Issue by cneumann** [danmarshall/deckgl-typings#128]
Hello,
`CompositeLayer.getSublayerProps` is currently typed as:
```typescript
getSubLayerProps(sublayerProps?: {}): {
    opacity: any;
    pickable: any;
    visible: any;
    parameters: any;
    getPolygonOffset: any;
    highlightedObjectIndex: any;
    autoHighlight: any;
    highlightColor: any;
    coordinateSystem: any;
    coordinateOrigin: any;
    wrapLongitude: any;
    positionFormat: any;
    modelMatrix: any;
    extensions: any;
};
```
Which causes problems if I want to use a custom layer that expects a certain (layer specific) prop in its input, for example:
```typescript
// Custom (composite) layer that requires a non-default prop named "layerSetting"

type InnerLayerData = Array<number>;
interface InnerLayerProps {
    layerSetting: number;
}

class InnerLayer extends CompositeLayer<InnerLayerData, InnerLayerProps> {
    // ...
}

// Another composite layer that makes use of InnerLayer
interface OuterLayerProps {
     layerSetting: number;
}

class OuterLayer extends CompositeLayer<OuterLayerData, OuterLayerProps> {
    renderLayers() {
        const {data, layerSetting} = props;
        return [
            new InnerLayer(
                this.getSublayerProps({
                    id: "inner-layer",
                    data,
                    layerSetting
                })
            )
        ];
    }
}
```
Typescript complains at the `new InnerLayer` line that the type returned by `getSublayerProps` does not contain `layerSetting` but it is required by InnerLayer.
I'm not sure it is possible to say anything about the return type of `getSublayerProps` in general, it may contain arbitrary props copied from its argument, so perhaps it should have a type argument that is the type of the props object it returns:
```typescript
getSubLayerProps<P extends LayerProps>(sublayerProps?: {}): P;
```
That allows me to say:
```typescript
            new InnerLayer(
                this.getSublayerProps<InnerLayerProps>({
                    id: "inner-layer",
                    data,
                    layerSetting
                })
            )
```

Or something along those lines - my minimal typescript knowledge is hitting its limits here, so maybe there's a more elegant way to express this?
I'll be happy to make a pull request for the above change if that is the desired resolution.

**Comment by danmarshall** [comment]
I'm pretty sure that `getSubLayerProps<P extends LayerProps>(sublayerProps?: {}): P;` is the way to go. Thanks for bringing this up, and I'll gladly take the PR. 👍

**Comment by cneumann** [comment]
Here's the PR. I had to add another type argument since LayerProps of course needs to know the "data" type of the layer.
