### ISSUE TITLE
Resolve conflicts between library and newly released `luma.gl` types

### ISSUE THREAD

**Issue by tombarton** [danmarshall/deckgl-typings#137]
`luma.gl` has released their own types as per version [8.3.0](https://github.com/visgl/luma.gl/blob/master/CHANGELOG.md#v830). These are conflicting with the types in this library when attempting to run tests. I'd suggest moving `luma.gl` to a dependency (maybe a peer dependency) and deprecating the appropriate types in favour of the official library.

Example errors below:

```
luma.gl__engine/index.d.ts:2:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: AnimationLoop, ProgramManager, Model, BufferTransform, TextureTransform, Transform, DRAW_MODE, Geometry, TruncatedConeGeometry, ConeGeometry, CubeGeometry, CylinderGeometry, IcoSphereGeometry, PlaneGeometry, SphereGeometry, Timeline, KeyFrames, ClipSpace

2 declare module "@luma.gl/engine/lib/animation-loop" {
  ~~~~~~~

  node_modules/@luma.gl/engine/dist/es5/index.d.ts:2:1
    2 declare module "@luma.gl/engine/lib/animation-loop" {
      ~~~~~~~
    Conflicts are in this file.
```

**Comment by danmarshall** [comment]
Oh, I see https://github.com/visgl/luma.gl/pull/1403
I agree in favor of deprecating this. We'll probably be bumping the major version for this.
