### ISSUE TITLE
DeckProps getTooltip type is missing `string`

### ISSUE THREAD

**Issue by argdiego** [danmarshall/deckgl-typings#155]
**Hi! Great work and thanks a bunch for the typings!**

### Issue: I noticed that the following function return type is missing `string`:

This function type is inside `DeckProps` and defines what type the `getTooltip?` property has, which can either be a string, an object (of particular type) or `null`. Below is its location:

https://github.com/danmarshall/deckgl-typings/blob/1910c32f35963bbcb68fed3d6a3f31624e355e36/deck.gl__core/index.d.ts#L2339

The function type above is currently:

```typescript
		getTooltip?: <D>(
			info: PickInfo<D>
		) => null | {
			text?: string;
			html?: string;
			className?: string;
			style?: {};
		};
```

When it should be:

```typescript
		getTooltip?: <D>(
			info: PickInfo<D>
		) => null | string | { // <-- change is here!
			text?: string;
			html?: string;
			className?: string;
			style?: {};
		};
```

...According to the Deck [documentation](https://deck.gl/docs/api-reference/core/deck#gettooltip) (screenshot below):

<img width="670" alt="Screen Shot 2021-02-18 at 4 54 41 PM" src="https://user-images.githubusercontent.com/72579829/108432453-01c72580-720a-11eb-9308-18b59f919db9.png">

I will review this more thoroughly first and submit a PR in the upcoming days if that's ok with the community.

Cheers!

Diego

**Comment by danmarshall** [comment]
Hi @argdiego thanks for the report. PRs are absolutely welcome, thanks for being a part of the community!

**Comment by argdiego** [comment]
Fix merged in PR https://github.com/danmarshall/deckgl-typings/pull/172
