### ISSUE TITLE
Trying to add minimal @deck.gl/arcgis support.

### ISSUE THREAD

**Issue by Davenporten** [danmarshall/deckgl-typings#168]
Full disclosure, I'm really new to typing declaration, I'm really familiar with ts, but I haven't done much with `.d.ts` files. That being said I'm trying to add the declaration for the `@deck.gl/arcgis` method `loadArcGISModules` (https://deck.gl/docs/api-reference/arcgis/load-arcgis-modules). I guess I have two questions when it comes to this:

1. Is there some reason why this is a bad idea or doesn't make any sense to do? I was surprised when arcgis wasn't present in this repo (I understand it's a living project and doesn't have everything in there), but it makes me wonder if there is a reason why it isn't in here beyond someone just not getting around to it.

2. Assuming it is something we want to have, my first attempt at the declaration is
```
declare module "@deck.gl/arcgis" {
  export function loadArcGISModules(
    modules: string[],
    loadScriptOptions: {
      version: string;
      url: string;
      css: string | boolean;
      insertCssBefore: string;
    }
  ): any;
}
```
Am I on the right track with this? When I try to use it in my project that's trying to use arcgis I get errors about `DeckLayer` (https://deck.gl/docs/api-reference/arcgis/deck-layer) being of type `any` and I'm not really sure how to proceed.

Anyway, I know these aren't well formulated questions, I'm mostly just kind of thrashing about trying to figure things out. Any help would be greatly appreciated!

**Comment by danmarshall** [comment]
Hi @Davenporten thanks for your willingness to jump in and try! It looks like `@deck.gl/arcgis` may have been an overlooked namespace. The way I bootstrapped these typings is with this script: https://github.com/danmarshall/deckgl-typings/blob/master/scripts/convert.js#L66 and I don't see that module here. I'll try adding it to see what I can get.

**Comment by danmarshall** [comment]
I've generated a starting point, please feel free to fill in any of the `any` types within to improve them. Thanks!

**Comment by danmarshall** [comment]
https://github.com/danmarshall/deckgl-typings/blob/master/deck.gl__arcgis/index.d.ts
