### ISSUE TITLE
Add `@deck.gl/carto`

### ISSUE THREAD

**Issue by alexkreidler** [danmarshall/deckgl-typings#184]
See https://deck.gl/docs/api-reference/carto/overview

Even just the most basic feature: the BASEMAP variable would be helpful. 

Thanks for this project!

**Comment by danmarshall** [comment]
Hello, it's been there for a couple of months :) - https://github.com/danmarshall/deckgl-typings/blob/master/deck.gl__carto/index.d.ts

Perhaps you don't have the latest version?

**Comment by alexkreidler** [comment]
Actually I do, I think I've found the issue: the `indefinitely-typed` `postinstall` command only installs the following packages:

```
deck.gl__aggregation-layers
deck.gl__core
deck.gl__extensions
deck.gl__geo-layers
deck.gl__google-maps
deck.gl__json
deck.gl__layers
deck.gl__mapbox
deck.gl__mesh-layers
deck.gl__react
deck.gl
luma.gl__constants
luma.gl__core
luma.gl__gltools
luma.gl__webgl-state-tracker
luma.gl__webgl
math.gl__core
math.gl
```

Which means they aren't copied to the `@types` folder. See below, the relevant part of `ls node_modules/@types/`:
```
deck.gl
deck.gl__aggregation-layers
deck.gl__core
deck.gl__extensions
deck.gl__geo-layers
deck.gl__google-maps
deck.gl__json
deck.gl__layers
deck.gl__mapbox
deck.gl__mesh-layers
deck.gl__react
fast-json-stable-stringify
flatbuffers
geojson
hammerjs
http-link-header
json-schema
lodash
lodash.mergewith
lru-cache
luma.gl__constants
luma.gl__core
luma.gl__gltools
luma.gl__webgl
luma.gl__webgl-state-tracker
mapbox-gl
math.gl
math.gl__core
```

Should be a quick fix. Thanks!

**Comment by danmarshall** [comment]
You're right, thanks! See #188
