### ISSUE TITLE
IconLayer: 'data' does not exist in type 'LayerProps'

### ISSUE THREAD

**Issue by Snaptags** [danmarshall/deckgl-typings#28]
I use `data` to pass the coordinates array to the IconLayer. Actually there isn't even an IconLayer in the definition files, my IDE is just jumping to the _Layer_ definition instead.

**Comment by danmarshall** [comment]
Would you mind adding these? A good example is TextLayerProps https://github.com/danmarshall/deckgl-typings/blob/master/deck.gl__layers/index.d.ts#L723

**Comment by danmarshall** [comment]
Published in [version 1.5.0](https://www.npmjs.com/package/@danmarshall/deckgl-typings) - thanks for pitching in!
