### ISSUE TITLE
PolygonLayerProps seems to be incomplete

### ISSUE THREAD

**Issue by Snaptags** [danmarshall/deckgl-typings#29]
Looking at the [deck.gl API doc](http://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer) I notice lots of PolygonLayerProps (I also use in my project code) that are not part of the typings yet, e.g. `filled`, `wireframe`, `elevationScale`…

Is there some kind of automatic progress for extracting properties from the deck.gl code?
Or may I just add missing stuff and submit a PR?

**Comment by danmarshall** [comment]
Hi @Snaptags, I don't have a process for props, but there is one implemented 
by @ibgreen https://github.com/uber/deck.gl/issues/1103#issuecomment-398940837 in this PR: https://github.com/uber/deck.gl/pull/1943

**Comment by danmarshall** [comment]
So, yes please file a PR, or better yet, automate it (for future versions) add to the [scripts](https://github.com/danmarshall/deckgl-typings/tree/master/scripts) folder.

**Comment by danmarshall** [comment]
Hi @Snaptags , can you see if this is fixed in the latest?

**Comment by Snaptags** [comment]
There is still one prop missing I use in my code: https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=positionformat-string-optional-
