### ISSUE TITLE
Layers need some kind of custom data field

### ISSUE THREAD

**Issue by Snaptags** [danmarshall/deckgl-typings#31]
In deck.gl layers often contain arbitrary user data to visualize stuff based on. For example: the polygon demo entry in the doc looks like this:
``` 
data: [
       { 
         contour: [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
         zipcode: 94107,
         population: 26599,
         area: 6.11
      }]
```
There has to be some kind of concept to deal with that. There could be a `payload: any` or `custom: any` field in every "LayerDatum" interface to allow the user to add all kinds of data to the layer…
``` 
data: [
       { 
         contour: [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
         custom: {
             zipcode: 94107,
             population: 26599,
             area: 6.11
          }
      }]
```

**Comment by MGHawes** [comment]
I believe this is fixed by #58 🙂

**Comment by Snaptags** [comment]
I checked out your branch and can verify that it is working perfectly. Will close this issue as soon as the PR has been merged. Thank you for the contribution.

**Comment by danmarshall** [comment]
Thanks @MGHawes & @Snaptags 🍻🍻
