### ISSUE TITLE
Luma.gl Dependency Outdated

### ISSUE THREAD

**Issue by ctaylor4874** [danmarshall/deckgl-typings#40]
The luma.gl dependency is outdated and causes Deck.gl to crash due to multiple versions on luma.  The correct version should be `"luma.gl": "^6.4.0"`

**Comment by danmarshall** [comment]
Thanks for reporting! It is only needed for authoring, i.e. devDependencies. Actually, it's only needed when running the [conversion script](https://github.com/danmarshall/deckgl-typings/blob/master/scripts/convert.js) which is a rare occurrence - only for a major revision of deck.gl. So let's remove it altogether for conflict avoidance.

**Comment by danmarshall** [comment]
published [2.2.1](https://www.npmjs.com/package/@danmarshall/deckgl-typings)
