### ISSUE TITLE
Cannot reproduce convert.js output

### ISSUE THREAD

**Issue by Snaptags** [danmarshall/deckgl-typings#42]
When I run the convert.js script I always get a ton of differences looking just like indentation issues to me:
![diff](https://user-images.githubusercontent.com/1249745/54992521-cdb43d00-4fbf-11e9-8e55-01818e4f3e26.png)

Any idea how to reproduce the results checked into the repo more exactly?

(it doesn't matter if I run the script using Ubuntu or Windows, same result … )

**Comment by danmarshall** [comment]
Hi @Snaptags - there's a lot of manual stuff that happens after I run the convert script. I just use autoformatting in vscode.

The convert script is just to bootstrap this project, after that we are back to manual additions. I run the convert script just to see the big areas that have changed between major versions.
