### ISSUE TITLE
not support deck v7?

### ISSUE THREAD

**Issue by petitlen** [danmarshall/deckgl-typings#43]
not support deck v7?

**Comment by danmarshall** [comment]
Nope not yet. See https://github.com/danmarshall/deckgl-typings#version-mapping

**Comment by petitlen** [comment]
1. such as ColumnLayer not support

**Comment by petitlen** [comment]
2. such as some Layer changed location

**Comment by petitlen** [comment]
ERROR in src/app/panels/mapbox/mapbox.component.ts(23,28): error TS2724: Module '"@deck.gl/layers"' has no exported member 'ColumnLayer'. Did you mean 'IconLayer'?

**Comment by danmarshall** [comment]
Typings for v7 now published: https://www.npmjs.com/package/@danmarshall/deckgl-typings
