### ISSUE TITLE
Support for deck.gl version 8.x.x

### ISSUE THREAD

**Issue by sedat** [danmarshall/deckgl-typings#62]
Hello, do you have any timeline for this?

https://github.com/uber/deck.gl/releases/tag/v8.0.1

We will be using this version for our application, so it would be our pleasure to assist you with the support for 8.x.x.

**Comment by danmarshall** [comment]
Thanks @sedat . As of now, I don't see the documentation for 8.x.x on https://deck.gl/#/documentation/overview/introduction so I'm unaware of what the breaking changes are from 7.x.x - that would be the starting point that we need.

**Comment by danmarshall** [comment]
OIC - https://github.com/uber/deck.gl/blob/master/docs/whats-new.md#deckgl-v80

**Comment by danmarshall** [comment]
I've asked what the breaking changes are in [this comment](https://github.com/uber/deck.gl/pull/4001#issuecomment-568814008). If there are no breaking changes, this task will be much easier as we only need to add new features.

**Comment by sedat** [comment]
Thank you for the quick reply @danmarshall . I will be waiting for the reply to that post as well. Here to help if you require any assistance.

**Comment by danmarshall** [comment]
Hi @sedat , I've created a new branch named `v8`. I have a pull request #64 which has a checklist of things I've read out of their what's new doc, let me know if I've missed anything. 

I do not have bandwidth to address the issues but they seem easy enough. Anyone who would like to    contribute please send PRs to the `v8` branch instead of `master`. Thanks!!

**Comment by mihaipanait** [comment]
@deck.gl/extensions should export also PathStyleExtension in v8. 
I get a TS error now on:
   import { PathStyleExtension } from '@deck.gl/extensions';

**Comment by danmarshall** [comment]
Thanks @mihaipanait - would you mind adding this and making a PR to the [v8 branch](https://github.com/danmarshall/deckgl-typings/tree/v8)?

**Comment by danmarshall** [comment]
Since this repo is *always* a work in progress, I've went ahead and bumped our major version to 4 which targets deck.gl v8. Known issues are in [the Readme](https://github.com/danmarshall/deckgl-typings#known-issues). Onward!

**Comment by danmarshall** [comment]
Regenerated v8 typings update now in 4.1.0
