### ISSUE TITLE
MapboxLayer should match CustomLayerInterface from mapbox-gl

### ISSUE THREAD

**Issue by danmarshall** [danmarshall/deckgl-typings#65]
@pacocom reports:
>Type 'MapboxLayer' is missing the following properties from type 'CustomLayerInterface': id, type

See [CustomLayerInterface via @types/mapbox-gl](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1f36fb3afd908ffa206570c4f0ecae4178f6944e/types/mapbox-gl/index.d.ts#L1581) and [deck.gl MapboxLayer source](https://github.com/uber/deck.gl/blob/master/modules/mapbox/src/mapbox-layer.js#L10)

**Comment by danmarshall** [comment]
@pacocom - this should be fixed in version 3.4.3

**Comment by pacocom** [comment]
Hello! 
Tanks! Very fast, but new problems:

This code content errors:
```
    const heatmapLayer = new MapboxLayer({
      data: this.locationData,
      type: HeatmapLayer,
      id: 'heatmap-layer',
      pickable: false,
      getPosition: d => [d[0], d[1]],
      getWeight: d => d[2],
      intensity: 1,
      threshold: 0.03,
      radiusPixels: 30,
    });
```
![image](https://user-images.githubusercontent.com/7735329/72414275-241e8200-3772-11ea-9679-d7fc3422d9dd.png)

**Argument of type '{ data: number[][]; type: typeof HeatmapLayer; id: string; pickable: false; getPosition: (d: any) => any[]; getWeight: (d: any) => any; intensity: number; threshold: number; radiusPixels: number; }' is not assignable to parameter of type 'MapboxLayerProps<number[]>'.
  Object literal may only specify known properties, and 'getPosition' does not exist in type 'MapboxLayerProps<number[]>'.**

This code does content errors:
```
    const heatmapLayer = new MapboxLayer({
      data: this.locationData,
      type: HeatmapLayer,
      id: 'heatmap-layer',
      pickable: false,
    });
    heatmapLayer.setProps({
      getPosition: d => [d[0], d[1]],
      getWeight: d => d[2],
      intensity: 1,
      threshold: 0.03,
      radiusPixels: 30,
    });
```

**Comment by danmarshall** [comment]
Does a little more typing help? This seems to make my compiler happy:
```
import { HeatmapLayer } from "deck.gl";
import { MapboxLayer } from "@deck.gl/mapbox";
import { HeatmapLayerProps } from "@deck.gl/aggregation-layers/heatmap-layer/heatmap-layer";

interface MyData {
    [index: number]: number;
}

const props: HeatmapLayerProps<MyData> = {
    getPosition: d => [d[0], d[1]],
    getWeight: d => d[2],
    intensity: 1,
    threshold: 0.03,
    radiusPixels: 30,
};

const heatmapLayer = new MapboxLayer({
    data: this.locationData,
    type: HeatmapLayer,
    id: 'heatmap-layer',
    pickable: false,
});

heatmapLayer.setProps(props);
```

**Comment by pacocom** [comment]
Yes, your last code is correct, but if you use the constructor code, it has error (as I wrote above):
```
 const heatmapLayer = new MapboxLayer({
      data: this.locationData,
      type: HeatmapLayer,
      id: 'heatmap-layer',
      pickable: false,
      getPosition: d => [d[0], d[1]],
      getWeight: d => d[2],
      intensity: 1,
      threshold: 0.03,
      radiusPixels: 30,
    });
```
Argument of type '{ data: number[][]; type: typeof HeatmapLayer; id: string; pickable: false; getPosition: (d: any) => any[]; getWeight: (d: any) => any; intensity: number; threshold: number; radiusPixels: number; }' is not assignable to parameter of type 'MapboxLayerProps<number[]>'.
Object literal may only specify known properties, and 'getPosition' does not exist in type 'MapboxLayerProps<number[]>'.

All examples use the constructor with this properties: getPosition, getWeight, intensity, threshold, radiusPixels,

Very Thanks!

**Comment by danmarshall** [comment]
I'm not sure how to make the TypeScript "smart" about the layer's props type, given that the only hint it has is the `type: HeatmapLayer`. If you want to keep the structure the same as their examples you might try this way of hinting:
```
const heatmapLayer = new MapboxLayer({
  data: this.locationData,
  type: HeatmapLayer,
  id: 'heatmap-layer',
  pickable: false,
  getPosition: d => [d[0], d[1]],
  getWeight: d => d[2],
  intensity: 1,
  threshold: 0.03,
  radiusPixels: 30,
} as MapboxLayerProps<MyData> & HeatmapLayerProps<MyData>);
```
