### ISSUE TITLE
Types are removed from `/node_modules/@types/<deckgl>` when other packages are added

### ISSUE THREAD

**Issue by tsaiDavid** [danmarshall/deckgl-typings#67]
Dan - thanks so much the work you've put into these typings so far!

## Notes
- Working out of a sample project I'm currently exploring, generated using [`tsdx`](https://github.com/jaredpalmer/tsdx)
- Using `yarn` to install dependencies, etc, complete with `yarn.lockfile`
- Using node@10.17, yarn@1.19.2

## Issues / Observations
- After installing additional package(s) with type definitions **after** a working setup exists, something appears to be removing the copied files from the `/node_modules/@types/<various_deckgl_folders>` directories
- Once you enter the "broken" state upon installing new typings, if you completely wipe out `node_modules` directory and re-run `yarn`, the issue appears to be resolved.

## Reproduce Error
- Repo here: https://github.com/tsaiDavid/deckgl-types-tsdx
- Instructions: https://github.com/tsaiDavid/deckgl-types-tsdx/blob/01-with-deckgl-types/README.md#reproduce-errors

**Comment by danmarshall** [comment]
Hi David, thanks for filing the issue.
Seems like Yarn is doing its job well, and tidying up node_modules. See [indefinitely-typed](https://github.com/danmarshall/indefinitely-typed) to understand how we put things into the `node_modules/@types` folder.

I'm not sure how to fix this, other than actually publishing to DefinitelyTyped. See #8 .

**Comment by tsaiDavid** [comment]
@danmarshall - no problem, I'd like to help where possible - just don't have prior experience ever publishing anything to DefinitelyTyped

**Comment by tsaiDavid** [comment]
@danmarshall - In the meantime, do you think modifying the `tsconfig.json` to include the following is a safe approach?

```   
"typeRoots": [
      "./node_modules/@types",
      "./node_modules/@danmarshall/deck-gl-typings"
    ],
```

**Comment by danmarshall** [comment]
@tsaiDavid - I don't have any experience with that config, but would like to know what you find out.

**Comment by tsaiDavid** [comment]
@danmarshall - The approach previously described seems to actually help for users of yarn, and in my case, even within a yarn workspace/lerna monorepo.

**Comment by danmarshall** [comment]
@tsaiDavid - that's awesome, thanks! If you'd like to add this to the Readme, I'll take a PR 🍻

**Comment by danmarshall** [comment]
Hi @tsaiDavid I just found a related project [patch-package](https://github.com/ds300/patch-package) which works in a similar way. They invoke [postinstall-postinstall](https://github.com/ds300/patch-package#why-use-postinstall-postinstall-with-yarn) for yarn users.

**Comment by mayteio** [comment]
Hey guys, thanks for the fix above. Any reason why the package hasn't been merged into DefinitelyTyped yet? The list in #8 hasn't been updated since 2018... so I'm guessing there's no action been made on them?

I can help get this ready for dt if you're keen to collaborate. We're relying on this package in a mapping package we've produced and don't want users of the package to have to reinstall it every time they add another package.

**Comment by danmarshall** [comment]
Hi @mayteio , you’re right, there’s been some activity for #8 but not enough to get to the quality bar for DT. So here’s a strategy: let’s start from the bottom of the stack and try to do one at a time. We know that at the bottom we have math.gl and luma.gl . I didn’t find and typings re-exposing math.gl so we could skip that for now. But there are some module references to luma.gl .
https://github.com/danmarshall/deckgl-typings/search?utf8=%E2%9C%93&q=luma

There’s about 300 `any`s in https://github.com/danmarshall/deckgl-typings/blob/db7b2008ce7fdde60e9856f21af5806ed08a4aac/luma.gl__core/index.d.ts 

I’m not sure if DT would accept this as-is or not. Perhaps you can try adding and find out if their automation will accept it?

**Comment by mayteio** [comment]
Yeah, I'll start there and report back. What's the process of finishing those declarations - is it manually working out what the `any`s are meant to be and filling out the definition file? What happens when you run `scripts/convert.js` in future, will that overwrite any manual changes that have been completed?

**Comment by danmarshall** [comment]
Yes the convert.js will overwrite everything. But it’s pretty easy to reconcile with a diff.

For finishing the definitions, I think there needs to be a test.d.ts file (which could be a lot of work?) and a lint.json file I believe.

**Comment by mayteio** [comment]
Correct - writing test uses for all would be a mammoth job. Shame Uber refuses to merge types into the project. 

I think that takes me back to square one. So, hypothetically my solution to this issue is:
```
1. add `postinstall-postinstall` to my package
2. add the script `,
    "postinstall": "cd ./node_modules/@danmarshall/deckgl-typings && npm run-script postinstall"` to my package.json
3. hope for the best?
```

**Comment by danmarshall** [comment]
If it helps adding postinstall-posinstall here, let me know.

**Comment by ChrisJamesC** [comment]
The portinstall command didn't work with me (with `npm` instead of `yarn`). If have added the following the file `types/deck.d.ts` instead: 

```
import * as DeckTypings from "@danmarshall/deckgl-typings"
declare module "deck.gl" {
    export module DeckTypings {}
}
```

And I have this in my `tsconfig.json`: 
```
{
  "compilerOptions": {...},  
  "typeRoots": [
    "./types",
    "./node_modules/@types"
  ],
}
```

I'd be happy to add this to the README if anyone else can verify that it solves the issue for them too.

**Comment by Snaptags** [comment]
> If have added the following the file `types/deck.d.ts` instead:
> 
> ```
> import * as DeckTypings from "@danmarshall/deckgl-typings"
> declare module "deck.gl" {
>     export module DeckTypings {}
> }
> ```

Thanks Chris, this worked for me. I did not have to change my tsconfig.json at all, just added the file.

**Comment by novakand** [comment]
I add as described in the Readme
```
import * as DeckTypings from "@danmarshall/deckgl-typings"
declare module "deck.gl" {
    export namespace DeckTypings {}
}

```
 
an error occurs ....@danmarshall/deckgl-typings/deck.gl/index.d.ts' is not a module
