### ISSUE TITLE
Line endings are in dos format and causes builds to fail on Mac

### ISSUE THREAD

**Issue by jkelleyrtp** [danmarshall/deckgl-typings#73]
```
Exit code: 127
Command: indefinitely-typed --folder deck.gl__core --folder deck.gl__layers --folder deck.gl__react --folder deck.gl --folder luma.gl --folder math.gl
Arguments: 
Directory:  <...>/node_modules/@danmarshall/deckgl-typings
Output:
env: node\r: No such file or directory
```

I can solve it by deleting the file in indefinitely-typed and remaking it with unix line breaks, but it will get overwritten on a fetch. Can we please fix this and roll out a change to npm?

**Comment by danmarshall** [comment]
Which files? Can you send a PR?

**Comment by jkelleyrtp** [comment]
I tried but I don't think git/github notices the line changes.

The issue is on cli.js in indefinitely typed and is breaking sanddance for me. 

I might be worth removing the file, committing, pushing, and then trying to merge my branch which doesn't have the windows carriage returns.

https://github.com/danmarshall/indefinitely-typed/pull/2

**Comment by danmarshall** [comment]
Yes, GitHub does not see any changes.

I do believe that there are other users pulling these typings on Macs. Also, the CI for SandDance is on Linux and has been running. Is it possible that you can tweak your personal git `autocrlf` settings?

**Comment by jkelleyrtp** [comment]
I don't see CI anywhere for SandDance, or if it's private, not sure what's going on behind the scenes. For me on macOS, 

```
git config --global core.autocrlf input
git clone https://github.com/danmarshall/deckgl-typings.git
cd deckgl-typings
yarn install

env: node\r: No such file or directory
```

I'm not sure what I can do - it seems that autocrlf set to input on mac only modifies anything I commit, not stuff already in the repository.

**Comment by jkelleyrtp** [comment]
Ah, indefintely-typed was updated 9 days ago in package.json. I don't think sanddance has run a CI build since then.

**Comment by danmarshall** [comment]
https://travis-ci.org/github/microsoft/SandDance

Here’s the link to Travis CI, we’ve done a few builds recently. Maybe you’ll be able to extract any config details from their setup?

**Comment by jkelleyrtp** [comment]
I somehow got it fixed but can't use the npm version, only versions pulled from git, which means I have to override it in resolutions with my branch.

https://github.com/danmarshall/indefinitely-typed/pull/3#issue-402388765

**Comment by ecerami** [comment]
@jkelleyrtp I am getting the same error here too.  How were you able to fix it on your end?

**Comment by danmarshall** [comment]
@ecerami - I just pushed @jkelleyrtp 's fix, can you make sure your `indefinitely-typed` is using 1.0.4 and see if this fixes it?

**Comment by jkelleyrtp** [comment]
1.0.4 Doesn't seem to do the trick. @ecerami In the package.json file that has a package that relies on indefinitely-typed, I put 

```
  "resolutions": {
    "indefinitely-typed": "github:jkelleyrtp/indefinitely-typed"
  }

```

and this seems to do the trick. I'm not sure if it's the fact that git does the auto-crlf or if npm just doesn't care.

On my fork, I deleted the file, merged it, and then readded the file with unix line endings. I don't think I can pull request into indefinitely-typed; it needs to be done in two commits.

**Comment by danmarshall** [comment]
@jkelleyrtp do you think this solution will work?:
https://stackoverflow.com/questions/32490412/how-can-i-configure-npm-to-use-windows-style-line-endings-in-package-json

**Comment by danmarshall** [comment]
@jkelleyrtp - you can also create a new file `cli2.js` and point to it from `package.json`

**Comment by mayteio** [comment]
Can confirm adding

```js
  "resolutions": {
    "indefinitely-typed": "github:jkelleyrtp/indefinitely-typed"
  }
```
to any package that relies on `@danmarshall/deckgl-typings` will solve the problem. However, this doesn't work in codesandbox.

**Comment by danmarshall** [comment]
Thank you all for reporting this issue. I've pushed a new `indefinitely-typed` package at version `1.1.0` which I hope fixes this issue. Please let me know if the update fixes on your machines. If so, I will bump the version here in `deck-gl-typings`.

**Comment by danmarshall** [comment]
https://github.com/danmarshall/indefinitely-typed/pull/4
