### ISSUE TITLE
Update Layer Position Typings to Allow for Elevation

### ISSUE THREAD

**Issue by dejajavvuu** [danmarshall/deckgl-typings#75]
The LineLayer (`getSourcePosition`/`getTargetPosition`) and PointCloudLayer (`getPosition`) interfaces do not allow for a z-value (elevation) since the typings are set to [number, number].

The typings should be updated to use the `Position` type defined in core/utils/positions:
```javascript
export type Position = [number, number] | [number, number, number];
```

**Comment by danmarshall** [comment]
Thanks @dejajavvuu ! Would you mind creating a PR?
