### ISSUE TITLE
Expose TextAnchor and AlignmentBaseline Types

### ISSUE THREAD

**Issue by dejajavvuu** [danmarshall/deckgl-typings#84]
Exposing these two definitions in the `@deck.gl/layers/text-layer/text-layer` module will allow users to set the `getTextAnchor` and `getAlignmentBaseline` properties of TextLayers.

**Comment by danmarshall** [comment]
I believe they are:
v7: https://github.com/danmarshall/deckgl-typings/blob/v3/deck.gl__layers/index.d.ts#L748
v8: https://github.com/danmarshall/deckgl-typings/blob/master/deck.gl__layers/index.d.ts#L998

**Comment by dejajavvuu** [comment]
My mistake!  Thanks!
