### ISSUE TITLE
Latest version does not include ReactDeckProps

### ISSUE THREAD

**Issue by ctaylor4874** [danmarshall/deckgl-typings#85]
The latest release does not include ReactDeckProps in the @deck.gl/react type defs. This causes errors when mounting `<DeckGL />` such as `viewState does not exist on...`

https://github.com/danmarshall/deckgl-typings/blob/546feb22699f764857a2883ae775132d061c634a/deck.gl__react/index.d.ts#L65-L66

**Comment by danmarshall** [comment]
Oh sorry about that! So many changes, I overlooked this. Fix is coming up

**Comment by danmarshall** [comment]
Published in 4.1.5

**Comment by ctaylor4874** [comment]
@danmarshall I think this is still missing a couple of things, I'll create a PR with fixes.
