### ISSUE TITLE
Unable to Set luma.gl Parameters on Layers

### ISSUE THREAD

**Issue by dejajavvuu** [danmarshall/deckgl-typings#87]
`parameters` is an unknown property for many layers.  I have seen it with at least LineLayer, ScatterPlotLayer, and PointCloudLayer.

**Comment by JannikGM** [comment]
I have a similar issue for a custom layer written from scratch, where this complains about `depthMask`:

```
  const layer = new CustomLayer({
    id: 'layer',
    image: image,
    parameters: {
      depthMask: false,
    }
  });
```

My custom-layer follows the style shown in #197.
