### ISSUE TITLE
TextLayer Updates

### ISSUE THREAD

**Issue by dejajavvuu** [danmarshall/deckgl-typings#89]
1. Update `getTextAnchor` to accept a function or string that returns a `TextAnchor` [(source documentation)](https://github.com/visgl/deck.gl/blob/master/docs/layers/text-layer.md#gettextanchor-functionstring-optional)
1. Update `getAlignmentBaseline` to accept a function or string that returns a `AlignmentBaseline` [(source documentation)](https://github.com/visgl/deck.gl/blob/master/docs/layers/text-layer.md#getalignmentbaseline-functionstring-optional)
1. Allow for `sizeMinPixels` and `sizeMaxPixels` rendering properties [(source documentation)](https://github.com/visgl/deck.gl/blob/master/docs/layers/text-layer.md#sizeminpixels-number-optional-)
1. Allow for `updateTriggers` dictionary

**Comment by stevenroussey-privicy** [comment]
Looks like #3 is already there, and #4 is already set as an any (could be Record<string, any> I guess).
